### PR TITLE
Duplicate model

### PR DESCRIPTION
**Pull request by lpalbou**
This PR requires first the bbop-manager-minerva PR to be merged: https://github.com/berkeleybop/bbop-manager-minerva/pull/2

This is a simple implementation of the model copy. The copy process takes between 1-20s depending of the size of the model. It still adds the person copying the model as a contributor (and still alter the dates of the original facts & annotations). 

Process: noctua landing page calls an asynchronous non-blocking method in bbop-manager-minerva, during which time noctua show a spinner. When finished, redirect to the new model page. If an error, display it in an alert box.

**Note**: an alternate way to duplicate the models would be to create the method directly in minerva. It would somewhat simplify the problem of handling the auto update of date & contributor fields and increase the copying speed by diminishing the amount of communication between barista / minerva.

@kltm could you merge that PR ? Let me know if you prefer me to direct it to the dev branch. I don't know which branch you are using for the deployment of the dev server.

### CODE REVIEW

**Comment by lpalbou** [comment]
I have read an issue about the Noctua-dev server but it seems we have a dependency problem (from travis):
```
npm ERR! peerinvalid The package jquery@2.2.4 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer selectize@0.12.6 wants jquery@^1.7.0, ^2, ^3
```

This does not appear locally.

Anyhow, don't merge yet, I have introduced a small issue this morning that I wish to correct first, thanks

**Comment by kltm** [comment]
I believe that some of the copying issues are still under discussion. We can revisit after the meeting.

**Comment by kltm** [comment]
@lpalbou I just want to clarify, before taking merge onto `dev`, but I'm assuming that you have some manual steps that you're using to test this as there has been no corresponding  release of bbop-manager-minerva and version bump?

**Comment by lpalbou** [comment]
I do have some manual tests, correct. I didn't created test units though.

**Comment by lpalbou** [comment]
@kltm since this is now the version on dev and was used successfully to duplicate models this morning, can I suggest this to be merged onto the dev branch?

**Comment by kltm** [comment]
@lpalbou From https://github.com/geneontology/noctua/pull/609#issuecomment-510709716 , I'm not understanding how you are testing/deploy this as there has been no correspond NPM release. I'm assuming you have some manual links when testing?

**Comment by lpalbou** [comment]
1 - I edited the doc of the noctua stack to explain how to create one from scratch
2 - I have a VM on AWS to spin up a full noctua stack
3 - that's the same VM that ben has been using for his tests some time ago

NPM release: of which package ? I see there are noctua and bbop-manager NPM packages under ktlm (probably should be under @geneontology) but they haven't been updated by anyone for some time.

**Comment by kltm** [comment]
For @kltm : release new bbop-manager version then increment package.json on this PR.

**Comment by lpalbou** [comment]
FYI, I don't think I have the sufficient rights to publish a new [bbop-manager NPM package](https://www.npmjs.com/package/bbop-manager-minerva). My NPM account is lpalbou

**Comment by kltm** [comment]
I'll get the updates in so the users can start looking at this and then we can schedule going back and dealing with https://github.com/geneontology/noctua/issues/620

**Pull request closed without merging**
