### PR TITLE
add some hardcoded relations to graph editor widget

### PR DESCRIPTION
**Pull request by kltm**
Add some additional requested relations to graph editor widget; for #801

### CODE REVIEW

**Comment by kltm** [comment]
@vanaukenk I wanted to check that these reflects the changes you wanted.
I'd note that the contents of the free-for-all section comes from the ontology and minerva, so we should look in that direction if there are issues in the lower section.

**Comment by vanaukenk** [comment]
Thank you @kltm 
I looked at the text of the code updates and it looks okay to me.
Let's update Noctua whenever you have time.

**Comment by kltm** [comment]
@vanaukenk I've added the changes to noctua-dev (e.g. http://noctua-dev.berkeleybop.org/editor/graph/gomodel:634db72e00000005 ). If this looks okay, I'll merge on `master` and rebuild. No downtime should be necessary.

**Comment by vanaukenk** [comment]
Thanks @kltm 
Things look good, except that the labels for 'indirectly negatively regulates' and 'indirectly positively regulates' are still showing in the editor as 'indirectly inhibits' and 'indirectly activates' even though they are correctly labeled in the pop-up window.
Do we need to bring minerva down to fix this bit?

**Comment by vanaukenk** [comment]
Hi @kltm 

Apologies, I just saw this comment:  https://github.com/geneontology/noctua/issues/801#issuecomment-1320729775

We'll want to have the labels fixed because we need GO-CAM models to use as examples for the documentation.

I'll also comment on the main ticket.

**Pull request merged**
