### PR TITLE
pointed the new Form Button on the landing to new NF

### PR DESCRIPTION
**Pull request by tmushayahama**
@kltm this will update the dead link [Add New Form] and row go to form on landing page

### CODE REVIEW

**Comment by kltm** [comment]
@tmushayahama This diff doesn't really work for me--I can't see the changes. Can you create a PR that's just the update?

**Comment by tmushayahama** [comment]
@kltm 

After renaming sae, the following were dead links on the landing. "sae" was hard coded We changed simple-annoton-editor and I just pointed it to NF.
image

**Comment by kltm** [comment]
Cheers! But what we have is the entire file nuked by the diff (thousands of small changes) for what should be a two-line diff. If we can update just the URL, it will make the git history more usable.

**Comment by kltm** [comment]
(And thank you for your patience here.)

**Comment by kltm** [comment]
Replaced by #634

**Pull request closed without merging**
