### PR TITLE
Create INSTALL

### PR DESCRIPTION
**Pull request by lpalbou**
Instructions to install a dev Noctua stack

### CODE REVIEW

**Comment by kltm** [comment]
This is really terrific! This should either be folded into the README.org (in favor of the related contents here) or that info should be taken out and point here.

**Comment by lpalbou** [comment]
@kltm Thanks, I merged both README and this new INSTALL + some rewrites. Feel free to adjust anything you want.

**Comment by kltm** [comment]
Whoops: https://github.com/geneontology/noctua/tree/proposal-install-commands
Org is not MD, so there are some display issues with that. We can either just change it to a README.md (probably for the best at this point) or make it an Org file. I'm almost caught up from last week, so I can take a crack at it in a bit if you want to leave it for now.

**Comment by lpalbou** [comment]
I didn't changed it as it was previously a .org and I thought there was maybe a reason for that. 
I have sent the commit for .md and will leave this PR as it is for now. Thanks

**Comment by kltm** [comment]
Awesome--thanks!
Yeah, a lot of early organization was done with Org and some of those documents remain, much to the confusion of anybody working with them.

**Comment by cmungall** [comment]
This is fantastic, thanks!

Should be pretty easy to turn this in to a Dockerfile, yep?

**Comment by lpalbou** [comment]
That would be a next logical step yes

For the moment, I just have an AWS AMI with this (equivalent of a VM), but it would be great to have each service as a container, including for other apps (e.g. golr, biolink, etc)

**Pull request merged**
