### PR TITLE
Update startup.yaml.stack-dev

### PR DESCRIPTION
**Pull request by lpalbou**
- Adding missing MINERVA_JAR field
- Changing MINERVA_MAX_MEMORY to 8 (won't start with 4). Note that other startup files use 64GB

### CODE REVIEW

**Comment by kltm** [comment]
@lpalbou Can you confirm the error message for 4G? Previously, 4G has squeaked by on my machine (I have it set low until I can transfer to another machine).

**Comment by lpalbou** [comment]
With 4G, here is the error message that I got:

`
2018-03-05 14:17:01,652 INFO  (StartUpTool:329) Start initializing Minerva
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.geneontology.rules.util.Bridge$.$anonfun$ruleFromJena$2(Bridge.scala:28)
	at org.geneontology.rules.util.Bridge$$$Lambda$181/337039263.apply(Unknown Source)
	at scala.Option.flatMap(Option.scala:171)
	at org.geneontology.rules.util.Bridge$.ruleFromJena(Bridge.scala:27)
	at org.geneontology.rules.util.Bridge$.$anonfun$rulesFromJena$1(Bridge.scala:24)
	at org.geneontology.rules.util.Bridge$$$Lambda$167/655059806.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$Lambda$43/711594948.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at org.geneontology.rules.util.Bridge$.rulesFromJena(Bridge.scala:24)
	at org.geneontology.rules.util.Bridge.rulesFromJena(Bridge.scala)
	at org.geneontology.minerva.CoreMolecularModelManager.initializeRuleEngine(CoreMolecularModelManager.java:291)
	at org.geneontology.minerva.CoreMolecularModelManager.<init>(CoreMolecularModelManager.java:198)
	at org.geneontology.minerva.BlazegraphMolecularModelManager.<init>(BlazegraphMolecularModelManager.java:112)
	at org.geneontology.minerva.MolecularModelManager.<init>(MolecularModelManager.java:73)
	at org.geneontology.minerva.UndoAwareMolecularModelManager.<init>(UndoAwareMolecularModelManager.java:176)
	at org.geneontology.minerva.server.StartUpTool.startUp(StartUpTool.java:330)
	at org.geneontology.minerva.server.StartUpTool.main(StartUpTool.java:239)
[14:20:02] 'run-minerva' errored after 5.1 min
[14:20:02] Error: Command `java -Xmx4G -cp ../minerva/minerva-cli/bin/minerva-cli.jar org.geneontology.minerva.server.StartUpTool --use-golr-url-logging --use-request-logging --slme-elk -g http://purl.obolibrary.org/obo/go/extensions/go-lego.owl --set-important-relation-parent http://purl.obolibrary.org/obo/LEGOREL_0000000 --port 6800 -f /tmp/blazegraph.jnl --export-folder /Users/albou/go-dev/noctua-models/models/ --golr-labels http://noctua-golr.berkeleybop.org --golr-seed http://amigo-dev-golr.berkeleybop.org` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
`

**Comment by kltm** [comment]
Gak.

**Comment by cmungall** [comment]
cc @bgood 

for testing/dev purposes, it should be possible to get the full stack running in <4gb.

**Comment by lpalbou** [comment]
@cmungall I'll cc him to see what can be removed from the startup sequence, but it works fine with 8G. For future reference, I have also tried with 6G but it's not sufficient.

**Pull request merged**
