### PR TITLE
Very hacky workbench for viewing all inference explanations.

### PR DESCRIPTION
**Pull request by balhoff**
This depends on functionality of https://github.com/geneontology/minerva/pull/123.

This is hacked from the Annotation Preview, which seems like it was hacked out of something else, so the code is pretty messy. Also it would be great if somebody could help show and hide the explanation cell with a button, and maybe in a popup instead of a table cell.

### CODE REVIEW

**Comment by balhoff** [comment]
@kltm I think this is ready to go. Needs the latest Minerva code. Travis is failing here - is that normal?

**Comment by kltm** [comment]
@balhoff sadly, yes--there is a ticket about that.

**Comment by kltm** [comment]
@balhoff The bulk of the changes would be pretty much:
```
	gpad_manager.export_model(global_id, 'inferredrelations');
```
? If so, it would probably better to put a selector on the ann preview workbench than have another workbench.

**Comment by kltm** [comment]
Added to https://github.com/berkeleybop/bbop-manager-minerva/wiki/MinervaRequestAPI

**Pull request merged**
