### PR TITLE
Bug Fixes. HPO Evidence Codes. UI_GRID improvements.

### PR DESCRIPTION
**Pull request by DoctorBud**
[View diffs without whitespace changes](https://github.com/geneontology/noctua/pull/376/files?w=1)

- Improves the eslint-compatibility of NoctuaBasicController.js
- Fixes bug where the default Disease title was blank when used with a
  non-lookup-enabled Minerva.
- Now the title is obtained from the autocomplete response.
- Improves the behavior of USE_UI_GRID and begins to unify the two modes
  in terms of underlying model.
- Deletes js/lib/noctua-widgetry/package.json.hiding which appears to
  have no purpose.
- Fixes several evidence/reference bugs and edge cases.
- Duplicate evidence when duplicating row.
- Improve the width available during autocomplete of a focused cell.
- Format evidence references and entity labels with nice indentation in
  case of word-wrap.
- Adds HPO Evidence codes and radio button selector.
- Cleans up naming of evidence-related vars in the code because it was
  very confusing.
- Deletes dead code.
- Fix issue where a non-HPO evidence code breaks the UI when found in an
  HPO model.
- Fix issue where the evidence reference is not enabled until tabbing
  out of the evidence code field.
- Fixes widgetry.user_check() to pass false for the group handler
- Ensures that legacy models without a default subject (disease) can
  still be read by using the per-association subject field as the
default.
- Removes the ITM evidence code from HPO Mode.
- Fix issues with AgeOfOnset and evidence codes when dealing with HPO
  TAB-to-PXF-OWL file imports.

### CODE REVIEW

**Comment by kltm** [comment]
Were there any actual changes in widgetry.js?

**Comment by DoctorBud** [comment]
No substantive changes to widgetry.js are in this PR, sorry about that.

I had made the same fix to widgetry that you had (ensuring that the group_change_announce was a function before calling it), and when I rebased against master, my change was moot and all that showed up was the trailing blank trimming.

I can modify the PR to backstep widgetry, or we can let it slide. Your choice, @kltm.

**Comment by kltm** [comment]
If it's just whitespace, I'd appreciate it if you wouldn't mind reverting. I'll take a look at why my ide seems to love injecting it periodically at end of line (although I prefer having it on empty lines and some comments).

**Comment by DoctorBud** [comment]
@kltm I reverted so that widgetry.js is no longer in this PR. Can I merge?

**Comment by jnguyenx** [comment]
It's been a while since I touched the Noctua code-based, but from what I can tell it looks good to me.

**Comment by kltm** [comment]
Looks good to me.

**Pull request merged**
