### PR TITLE
Autosave, tighter layout, less buttons, less pre-save constraints, HPO/Monarch Choice, more readable autocomplete, autoscroll/autofocus on edit.

### PR DESCRIPTION
**Pull request by DoctorBud**
- Remove unused xeditable dependency.
- Reduce font-size of selectize widgets.
- Position feedback label above selectize widget.
- Organize rows horizontally instead of in card-mode.
- Improves gulpfile so that gulp watch only compiles Basic if that is
  all that is needed.
- Adds in conditional code to support ui-grid and ui-select. Look for
  USE_UI_GRID. Currently disabled.
- ESLint added to tooling, .eslintrc added
- Adds ability to save and reload a model that has a default subject
  (disease).
- Hides Disease column.
- Prepopulating new rows with default subject (disease).
- Fixes layout to minimize horizontal scrolling.
- Centers action buttons. The per-annotation action buttons no longer
  wrap weirdly.
- Less-white-space version of the annotation table.
- The Add New Annotation button move up into the per-model button
  section.
- Tightens up layout of Disease/Title
- Autosave is now in place, which means that after saving a new or
  edited association, the entire model is saved to disk.
- An association row can be saved as long as it at least has a phenotype
  specified. It can subsequently be edited and other values added (e.g.,
AgeOfOnset, Evidence).
- The Save, Delete, Export and Graph buttons have been removed, as has
  the containing panel footer, leaving more screen space for
associations.
- The Add Annotation button is now a Plus-Sign button on the corner of
  the Association list.
- Buttons are now less color and ink-heavy.
- The Tooltips on the graphical buttons are clearer (visible if you
  hover over them).
- Improves placeholder alignment in input fields.
- Fixes autocomplete queries to use the closure that is rooted at a particular ontology id.
- Cleans up the help text for Noctua and WebPhenote.
- Enables ability to choose which profile to use at creation time, and to enforce this profile upon subsequent editing (e.g., the HPO restriction).
- Autoscroll/focus to the Phenotype column of a new or edited association row
- Fix gulpfile to not use us.union() for concatenation of arrays.
- Delete dead disease selection code.

### CODE REVIEW

**Comment by cmungall** [comment]
A lot of this looks straightforward, but I expect the parts that touch the core need to be looked at

**Comment by DoctorBud** [comment]
If it helps, we can schedule a Skype/Zoom session where we walk through the diffs at high speed. Many of the changes are to speed up or improve development. For example, the `gulp watch` task now spawns two tasks, each of which watches the appropriate subset of files. That way, Noctua devs don't have to endure unnecessary WebPhenote compilation and vice versa.

Most of the changes are involved in making the WebPhenote form interface look nicer, and it shouldn't affect Noctua.

I did make some changes to the way that the Landing text, the About text and the Overview text are dealt with. This may affect (or complement) this PR https://github.com/geneontology/noctua/pull/323.

The only *core* changes I would be concerned with are:
- I modified `noctua.js` so that it established a new global variable in the pup_tent global list called `model_type`, which I use to let the WebPhenote `/basic` controller know whether we are in 'monarch' or 'hpo' mode. I don't think it will affect Noctua (I tested in NOCTUA_CONTEXT=go as well as =monarch).
- In order for me to record in the OWL model what *intent* the user had (model_type===hpo or model_type===monarch), so that I can apply those preferences during subsequent editing, I added a `dc11:type` annotation to the model (at the same level as the `title`).
- In order for me to record in the OWL model the user's default disease (generalized to *subject*), I added an annotation using  `dc11:subject`, which records the URI for the disease the user selects upon initial creation of a WebPhenote model.

The annotation choices above were made without consulting with you, and they are changeable.

The other *risky behavior* I indulged in was to upgrade many of the NPM modules used, but I have not observed any problems.

**Comment by kltm** [comment]
@DoctorBud Hm. I'm unable to use current configuration files with your fork. It looks like you've changed at least the ONTOLOGY_CATALOG variable name?

**Comment by kltm** [comment]
Looking at templates/noctua_base.tmpl, I think it's better to be consistent and have local hosting be the base, with CDNs as an option if necessary.

**Comment by cmungall** [comment]
I assume things like hpo mode and monarch mode are temporary - we want to avoid procedural configuration

**Comment by kltm** [comment]
Like you said, it might be better to go through this a bit on zoom/skype, but I'd like a chance to run it locally first so we don't have to waste your time by circling around. I'll take a shake at working around the variable problems tomorrow locally, then maybe we could touch bases in the afternoon sometime?

**Comment by DoctorBud** [comment]
Thanks for the comments...

I agree about the CDN usage in `noctua_base.tmpl`. That is incorrect and I am fixing it so the assets are bundled.

Regarding the *unable to use existing configuration files*, I do not think I changed the configuration file format since my last PR, where I added `NOCTUA_CONTEXT`. The `ONTOLOGY_CATALOG` variable has always been part of the world I thought.

I think that the configuration problem you are seeing can be fixed by removing the slashes from your `GOLR_LOOKUP_URL` and `GOLR_NEO_LOOKUP_URL` values, because I have a workaround in the `gulpfile.js` to deal with Minerva adding a trailing slash and creating an unparseable path. In hindsight, my workaround is sloppy and I am going to make it nicer so that you can have a slash or not and the gulpfile will ensure that Minerva is called without a slash (fixing Minerva would be nice, but I tried to avoid creating a dependency).

I've rebased from the latest master and will have a revised PR today or tomorrow.

**Comment by kltm** [comment]
@DoctorBud The changes seems to be between the ONTOLOGY_CATALOG (master) and GENEONTOLOGY_CATALOG (fork) variables. This occurs in both the config examples and the gulpfile.js.

**Comment by kltm** [comment]
https://github.com/geneontology/noctua/pull/319#issuecomment-242218574 cleared with @DoctorBud on skype.

**Comment by DoctorBud** [comment]
Just updated the PR with this commit:
- Removes CDN versions of selectize.css and select2.css.
- Fixes gulpfile.js so that trailing slashes on GOLR_LOOKUP_URL and GOLR_NEO_LOOKUP_URL are not necessary.
- Comments out currently unused ui-grid refs

**Comment by kltm** [comment]
I was still having the deploy directory creation issue; after some messing around, it cleared by changing to Node.js LTS 4. In this case, 0.12.2 is still in the package.json. I think we need more pre-coordination for changes libraries and versions.

While I haven't tested everything yet, it seems there is a problem with either compilation or delivery of workbenches, erring like:
```
ReferenceError: model_type is not defined
    at /home/sjcarbon/local/src/git/noctua-monarch/noctua.js:778:30
    at Layer.handle [as handle_request] (/home/sjcarbon/local/src/git/noctua-monarch/node_modules/express/lib/router/layer.js:95:5)
```

In the future, smaller, and more frequent, PRs would be preferable to larger ones, and might make teasing apart merge issues a little more clear.

**Comment by DoctorBud** [comment]
Thanks. I'll amend the PR to fix the model_type bug and make the NodeJS version ensure 4.x.

**Comment by kltm** [comment]
Cheers--I'll continue testing on the next commit.
Also, how long does it take, typically, to deal with merges against master? I'm trying to get some features done for a meeting next week, but don't want to get too conflicty with what you're working on.

**Comment by DoctorBud** [comment]
Fixed the `model_type` problem. Tested in a `go` configuration and verified that the example workbench loaded fine (it crashed before my fix, as @kltm reported). Tests are running. Going to get dinner.

**Comment by kltm** [comment]
Okay, I finally had a chance to dig in a bit more. A few comments from things I ran across; some of them are just comments into the air for now. I think 1, 6, and maybe 7 would be good to get feedback/changes. I'll test a little more tomorrow, then take the PR.

1. the node version needs to be upped in the package.json to current 4 LTS
2. not wild about the .eslintrc in there, but I'm just using jshintrc right now, so no collision yet
3. thank you for the improvements in the gulpfile.js (I may poke a couple of things after the merge)
4. digging more into it, I can see that it is looking like the seeds of a secondary client; something to think about--it may be better to split at some point then to keep too many switches in; also I see that you have the model_type showing up in the path, hm
5. thank you for the package upgrades
6. is jsdoc-baseline no longer needed? E.g. is a decent style now default?
7. client tri-state: currently, there are three subclients running around: "go", "monarch", and "open"; I think that everything I saw is correct for that, with the defaults being monarch-exclusive, but I didn't recheck all the conditionals yet, I just wanted to make sure you had that in mind

I may poke a couple of things after the merge, just to re-orient myself, but it's looking really good and pretty much ready to go. Awesome~!

**Comment by kltm** [comment]
@DoctorBud Hm. Where are you getting your npm from? The version I have is packaged with nodejs, which I'd assume would be the right one to use, and behind your latest:
```shell
sjcarbon@moiraine:~/local/src/git/noctua$:) dpkg -S /usr/bin/npm
nodejs: /usr/bin/npm
sjcarbon@moiraine:~/local/src/git/noctua$:) node -v
v4.5.0
sjcarbon@moiraine:~/local/src/git/noctua$:) npm -v
2.15.9
sjcarbon@moiraine:~/local/src/git/noctua$:) 

```

**Comment by kltm** [comment]
@DoctorBud To clarify, I'm using the LTS package/repo provided by node upstream.

**Comment by DoctorBud** [comment]
NPM2 and NPM3 are slightly different in how they handle dependencies. See https://docs.npmjs.com/how-npm-works/npm3

I had no idea that NPM2 was in the standard distro, because I don't use the standard distro. I usually just do `npm install -g npm@latest` and get 3.x. For Monarch, our .travis.yml explicitly installs npm3, which may be unnecessary, but I recall that NPM2 gave us trouble.

I have not tested with NPM2, so I can't currently vouch for it. It appears that v2 and v3 have security-patch parity (i.e., they are both actively being developed).

I will test on NPM2 and make sure everything works, and if so,  I'll turn the NPM version back to 2. Thanks for the feedback.

**Comment by DoctorBud** [comment]
I updated package.json to specify node4.4+ and npm2.15+. I used 4.4+ because 4.4 is where I've done most of my testing, although Node4.5 is the latest LTS.

```
     "node": ">= 4.4",
      "npm": ">= 2.15"
```

**Comment by kltm** [comment]
We can update and sort it all later. Apologies for the delay.

**Comment by kltm** [comment]
@DoctorBud Another hiccup I ran into today with the library upgrade (I wanted to document this somewhere for future reference). It turns out that the upgraded library set pulls in a module that cannot compile on the version of gcc that is on Ubuntu 12.04 LTS (gcc 4.6.3).
E.g.:
```
/home/swdev/.node-gyp/4.5.0/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
...
../node_modules/nan/nan_maybe_43_inl.h:19:12: error: ‘Maybe’ does not name a type
...
In file included from ../node_modules/nan/nan.h:187:0,
                 from ../src/microtime.cc:9:
../node_modules/nan/nan_converters.h:14:11: error: ‘MaybeLocal’ does not name a type
...
npm ERR! sleep@3.0.0 install: `node-gyp rebuild`
```
a la: http://stackoverflow.com/questions/33532528/nodejs-4-5-npm-install-fail-for-bcrypt-and-db-migrate
I'll go ahead and migrate that machine up on Monday, as I don't think it's really possible to walk back the libraries, but we should keep an eye on external system dependencies like that for future upgrades/releases.

**Pull request merged**
